version: '3'

services:
  jupyter:
    build: .
    container_name: jupyter_container
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
