version: "3"

services:
  jupyter:
    build: .
    container_name: jupyter_container
    volumes:
      - .:/home/jovyan/project
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    working_dir: /home/jovyan/project
